---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
# load packages
library(here)
library(tidyverse)
```

```{r}
# read csv files
ice_duration <- read.csv(here("data", "ntl33_v7.csv"), na = -999)

meteorlogical <- read.csv(here("data", "ntl20_v6.csv"), na = -999)
```

```{r}
mean <- ice_duration %>%
  group_by(lakeid) %>%
  summarize(mean_ice = mean(ice_duration, na.rm = TRUE))
```


```{r}
ggplot(data = ice_duration, aes(x = ice_duration, 
                               y = lakeid)) + 
  geom_jitter() +
  geom_boxplot(alpha = 0.1, color = "red") +
  theme_classic() +
  labs(x = "Ice Duration", y = "Lake")

```

```{r}
# mean duration by year
mean_ice <- ice_duration %>%
  group_by(year4) %>%
  summarize(mean_ice = mean(ice_duration, na.rm = TRUE))
```

```{r}
ggplot(data = mean_ice, aes(x = year4, y = mean_ice)) +
  geom_point() +
  geom_smooth(color = "red") +
  theme_classic() +
  labs(x = "Year", y = "Mean")
```

```{r}
mean_air <- meteorlogical %>%
  filter(month %in% c("12", "1", "2")) %>%
  group_by(year4) %>%
  summarize(mean_air = mean(ave_air_temp_adjusted, nar.rm = TRUE))
```

```{r}
ggplot(data = mean_air, aes(x = year4, y = mean_air)) +
  geom_point() +
  geom_smooth(color = "red") +
  theme_classic() +
  labs(x = "Year", y = "Average Air Temp")
```

```{r}
join <- full_join(mean_air, mean_ice, by = "year4")
```

```{r}
ggplot(data = join, aes(x = mean_air, y = mean_ice)) + 
  geom_point() +
  geom_smooth(color = "red") +
  theme_classic() +
  labs(x = "Average Air Temp", y = "Average Ice Duration")
```


